Repository illuin-tech/colpali, pull requests merged in 2025-02, with the labels that each got.

#183 Remove inference example script
  README.md
  scripts/infer/run_inference_with_python.py
Labels: documentation

#181 Add token pooling
  CHANGELOG.md
  README.md
  colpali_engine/compression/__init__.py
  colpali_engine/compression/token_pooling.py
  pyproject.toml
  tests/compression/__init__.py
  tests/compression/test_token_pooling.py
Labels: enhancement

#184 Start token pooling cluster ids from 0
  colpali_engine/compression/token_pooling.py
  tests/compression/test_token_pooling.py
Labels: enhancement

#187 Improve token pooling + add multithreading support
  README.md
  colpali_engine/compression/token_pooling.py
  colpali_engine/utils/torch_utils.py
  tests/compression/test_token_pooling.py
  tests/utils/test_torch_utils.py
Labels: enhancement

#188 Fix token pooling output dtype
  colpali_engine/compression/token_pooling.py
Labels: bug

#190 Add num workers option for token pooling
  colpali_engine/compression/token_pooling.py
Labels: enhancement

#185 Update CHANGELOG for `v0.3.9`
  CHANGELOG.md
  README.md
Labels: documentation

#191 Fix issue when using ColQwen2 with MPS
  README.md
  tests/models/qwen2/colqwen2/test_modeling_colqwen2.py
Labels: bug

#192 remove results being stored
  CHANGELOG.md
  colpali_engine/trainer/colmodel_training.py
Labels: enhancement

#175 ColQwen2.5
  CHANGELOG.md
  README.md
  colpali_engine/__init__.py
  colpali_engine/models/__init__.py
  colpali_engine/models/qwen2_5/__init__.py
  colpali_engine/models/qwen2_5/colqwen2_5/__init__.py
  colpali_engine/models/qwen2_5/colqwen2_5/modeling_colqwen2_5.py
  colpali_engine/models/qwen2_5/colqwen2_5/processing_colqwen2_5.py
  pyproject.toml
  tests/models/qwen2_5/colqwen2_5/test_modeling_colqwen2_5.py
  tests/models/qwen2_5/colqwen2_5/test_processing_colqwen2_5.py
Labels: new model

#199 Fix ColQwen2/2.5 attention when no CUDA device
  CHANGELOG.md
  README.md
  colpali_engine/models/qwen2/colqwen2/modeling_colqwen2.py
  colpali_engine/models/qwen2_5/colqwen2_5/modeling_colqwen2_5.py
  tests/models/qwen2/colqwen2/test_modeling_colqwen2.py
  tests/models/qwen2_5/colqwen2_5/test_modeling_colqwen2_5.py
Labels: bug

#203 Replace ColQwen2 MPS hotfix with user warning
  CHANGELOG.md
  colpali_engine/models/qwen2/colqwen2/modeling_colqwen2.py
  colpali_engine/models/qwen2_5/colqwen2_5/modeling_colqwen2_5.py
Labels: bug
